In [1]:
import numpy as np
from sad_construct import *
from sad_read_cifar10 import get_cifar10
(x_train,y_train),(x_test,y_test)=get_cifar10()
x_train=x_train.reshape(-1,3*32*32)
x_test=x_test.reshape(-1,3*32*32)
cifar10_train_data = np.append(x_train, y_train, axis=1)
cifar10_test_data = np.append(x_test, y_test, axis=1)
cifar10_shape=(3,32,32)

In [2]:
train_and_test(
    mynetwork=cnn_cifar10,
    train_data=cifar10_train_data,
    test_data=cifar10_test_data,
    data_shape=cifar10_shape,
    onehotsize=10,
    batch_size=16,
    epoch_num=20,
    half_learning_rate_time=5,
    pth="cnn_cifar10.npy"
)


epoch 1:
 Loss:0.621773440 	Accuracy: 0.6688 [0.745, 0.873, 0.684, 0.529, 0.489, 0.589, 0.709, 0.699, 0.799, 0.572]
epoch 2:
 Loss:0.604697813 	Accuracy: 0.6963 [0.754, 0.752, 0.572, 0.494, 0.602, 0.525, 0.836, 0.8, 0.831, 0.797]
epoch 3:
 Loss:0.585763745 	Accuracy: 0.6877 [0.683, 0.749, 0.618, 0.461, 0.596, 0.669, 0.726, 0.783, 0.776, 0.816]
epoch 4:
 Loss:0.570935702 	Accuracy: 0.6849 [0.82, 0.744, 0.64, 0.401, 0.595, 0.567, 0.775, 0.729, 0.769, 0.809]
epoch 5:
 Loss:0.552346228 	Accuracy: 0.6946 [0.74, 0.825, 0.65, 0.429, 0.768, 0.525, 0.785, 0.669, 0.782, 0.773]
epoch 6:
 Loss:0.540152195 	Accuracy: 0.6867 [0.698, 0.842, 0.655, 0.458, 0.571, 0.513, 0.769, 0.74, 0.849, 0.772]
epoch 7:
 Loss:0.525218568 	Accuracy: 0.6886 [0.753, 0.688, 0.657, 0.557, 0.596, 0.487, 0.777, 0.765, 0.772, 0.834]
epoch 8:
 Loss:0.512682451 	Accuracy: 0.6869 [0.738, 0.697, 0.603, 0.539, 0.598, 0.61, 0.834, 0.668, 0.771, 0.811]
epoch 9:
 Loss:0.495785392 	Accuracy: 0.694 [0.762, 0.774, 0.593, 0.421, 0.656, 

In [3]:
train_and_test(
    mynetwork=LeNet5_cifar10,
    train_data=cifar10_train_data,
    test_data=cifar10_test_data,
    data_shape=cifar10_shape,
    onehotsize=10,
    batch_size=16,
    epoch_num=20,
    half_learning_rate_time=5,
    pth="LeNet5_cifar10.npy"
)

init para
epoch 1:
 Loss:1.922219159 	Accuracy: 0.406 [0.492, 0.523, 0.175, 0.182, 0.536, 0.369, 0.544, 0.446, 0.371, 0.422]
epoch 2:
 Loss:1.592144013 	Accuracy: 0.462 [0.376, 0.682, 0.401, 0.233, 0.299, 0.471, 0.47, 0.604, 0.618, 0.466]
epoch 3:
 Loss:1.478148090 	Accuracy: 0.4798 [0.514, 0.77, 0.293, 0.216, 0.357, 0.493, 0.729, 0.561, 0.372, 0.493]
epoch 4:
 Loss:1.409167035 	Accuracy: 0.4947 [0.603, 0.5, 0.374, 0.272, 0.221, 0.521, 0.745, 0.588, 0.546, 0.577]
epoch 5:
 Loss:1.352145361 	Accuracy: 0.5003 [0.422, 0.63, 0.327, 0.31, 0.335, 0.307, 0.839, 0.666, 0.547, 0.62]
epoch 6:
 Loss:1.298472515 	Accuracy: 0.5339 [0.613, 0.755, 0.293, 0.355, 0.417, 0.304, 0.749, 0.634, 0.665, 0.554]
epoch 7:
 Loss:1.245916749 	Accuracy: 0.5524 [0.496, 0.683, 0.413, 0.279, 0.535, 0.469, 0.595, 0.707, 0.654, 0.693]
epoch 8:
 Loss:1.195568580 	Accuracy: 0.5634 [0.578, 0.78, 0.439, 0.38, 0.45, 0.483, 0.583, 0.618, 0.726, 0.597]
epoch 9:
 Loss:1.152158322 	Accuracy: 0.5733 [0.606, 0.685, 0.467, 0.262, 

In [4]:
only_test(
    mynetwork=cnn_cifar10,
    test_data=cifar10_test_data,
    data_shape=cifar10_shape,
    onehotsize=10,
    pth="cnn_cifar10.npy"
)

Accuracy: 0.6749 [0.734 0.843 0.584 0.365 0.569 0.624 0.671 0.766 0.821 0.772]
Cross Accuracy:
[[0.734 0.032 0.034 0.01  0.013 0.014 0.005 0.006 0.104 0.048]
 [0.015 0.843 0.    0.003 0.002 0.003 0.003 0.004 0.031 0.096]
 [0.086 0.013 0.584 0.044 0.068 0.072 0.038 0.047 0.037 0.011]
 [0.032 0.032 0.07  0.365 0.064 0.243 0.052 0.064 0.043 0.035]
 [0.033 0.011 0.105 0.046 0.569 0.055 0.035 0.113 0.026 0.007]
 [0.024 0.026 0.058 0.087 0.033 0.624 0.018 0.098 0.012 0.02 ]
 [0.011 0.043 0.066 0.047 0.047 0.051 0.671 0.017 0.017 0.03 ]
 [0.02  0.011 0.029 0.023 0.051 0.058 0.006 0.766 0.013 0.023]
 [0.068 0.051 0.006 0.008 0.005 0.004 0.001 0.004 0.821 0.032]
 [0.023 0.128 0.011 0.006 0.003 0.007 0.002 0.016 0.032 0.772]]


In [2]:
train_and_test(
    mynetwork=Fc_cifar10,
    train_data=cifar10_train_data,
    test_data=cifar10_test_data,
    data_shape=cifar10_shape,
    onehotsize=10,
    batch_size=16,
    epoch_num=20,
    half_learning_rate_time=5,
    pth="fc_cifar10.npy"
)


init para
epoch 1:
 Loss:1.839917913 	Accuracy: 0.4077 [0.547, 0.471, 0.388, 0.123, 0.294, 0.406, 0.546, 0.301, 0.537, 0.464]
epoch 2:
 Loss:1.643068802 	Accuracy: 0.4387 [0.515, 0.609, 0.495, 0.115, 0.206, 0.371, 0.483, 0.467, 0.678, 0.448]
epoch 3:
 Loss:1.556201690 	Accuracy: 0.4539 [0.515, 0.531, 0.401, 0.334, 0.236, 0.327, 0.653, 0.502, 0.695, 0.345]
epoch 4:
 Loss:1.494295085 	Accuracy: 0.4769 [0.616, 0.655, 0.162, 0.239, 0.288, 0.481, 0.542, 0.726, 0.613, 0.447]
epoch 5:
 Loss:1.442280935 	Accuracy: 0.4825 [0.503, 0.458, 0.309, 0.254, 0.377, 0.529, 0.667, 0.541, 0.63, 0.557]
epoch 6:
 loss:1.795122288 	process: 67.96%	   

KeyboardInterrupt: 